; Standalone Friend or Foe backend Lite scanner firmware.

[platformio]
src_dir = main
default_envs = scanner-s3-combo-backend

[env:scanner-s3-combo-backend]
platform = espressif32@6.13.0
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 921600
board_upload.flash_size = 8MB
board_upload.offset_address = 0x20000
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions_backend_scanner_8mb.csv
build_flags =
    -DFOF_BACKEND_FIRMWARE=1
    -DFOF_BACKEND_SCANNER=1
    -DBOARD_HAS_PSRAM
