[platformio]
src_dir = main
default_envs = uplink-s3-backend

[env:uplink-s3-backend]
platform = espressif32@6.13.0
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 921600
board_upload.flash_size = 8MB
board_upload.offset_address = 0x20000
board_build.partitions = partitions_backend_uplink_8mb.csv
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.psram_type = opi
build_flags =
    -DFOF_BACKEND_FIRMWARE=1
    -DFOF_BACKEND_UPLINK=1
    -DBOARD_HAS_PSRAM
