"""Offline RF reference resolver.

Live RF observations must never be submitted to third-party lookup services.
This module only reads the committed artifact generated by
``scripts/update_rf_reference_data.py`` plus local operator overrides.
"""

from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass
from fnmatch import fnmatchcase
from pathlib import Path
from typing import Any

from app.services.oui_db import is_random_mac as _legacy_is_random_mac

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
REFERENCE_PATH = DATA_DIR / "rf_reference.json"

SOURCE_LABELS = {
    "ieee_ma_l": "IEEE RA MA-L",
    "ieee_ma_m": "IEEE RA MA-M",
    "ieee_ma_s": "IEEE RA MA-S",
    "ieee_cid": "IEEE RA CID",
    "wireshark_manuf": "Wireshark manuf",
    "nmap_mac_prefixes": "Nmap mac-prefixes",
    "bluetooth_company_ids": "Bluetooth SIG Assigned Numbers",
    "bluetooth_sig": "Bluetooth SIG Assigned Numbers",
    "local_ble_company_ids": "Local BLE company fallback",
    "operator_ssid_override": "Operator RF override",
    "ssid_pattern": "Local SSID pattern",
    "friendly_oui": "Operator curated OUI hint",
    "group_oui_majority": "Group public-OUI majority",
    "apple_continuity": "Apple Continuity BLE evidence",
    "wifi_fingerprint_v2": "WiFi fingerprint v2",
    "drone_signature_reference": "Curated drone SSID reference",
    "randomized_mac": "Randomized/private MAC rule",
    "none_randomized_mac": "No vendor from randomized MAC",
}

STATIC_SOURCE_URLS = {
    "operator_ssid_override": "local:backend/app/data/rf_overrides.yaml",
    "ssid_pattern": "local:backend/app/data/rf_overrides.yaml",
    "friendly_oui": "local:backend/app/data/rf_overrides.yaml",
    "group_oui_majority": "local:derived/group-public-oui-majority",
    "apple_continuity": "https://github.com/furiousMAC/continuity",
    "wifi_fingerprint_v2": "local:derived/wifi-ie-auth-channel-fingerprint",
    "drone_signature_reference": "local:backend/app/services/drone_signature_reference.py",
    "randomized_mac": "local:derived/mac-locally-administered-bit",
    "none_randomized_mac": "local:derived/no-mac-vendor-for-randomized-address",
}


@dataclass(frozen=True)
class MacResolution:
    vendor_short: str | None
    vendor_long: str | None
    vendor_aliases: list[str]
    vendor_source: str | None
    assignment_type: str | None
    prefix_bits: int | None
    oui_prefix: str | None
    product_hint: str | None
    device_family: str | None
    device_class: str | None
    vendor_confidence: float
    reference_updated_at: str | None
    mac_is_randomized: bool
    mac_identity_kind: str
    mac_reason: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "vendor_short": self.vendor_short,
            "vendor_long": self.vendor_long,
            "vendor_aliases": self.vendor_aliases,
            "vendor_source": self.vendor_source,
            "assignment_type": self.assignment_type,
            "prefix_bits": self.prefix_bits,
            "oui_prefix": self.oui_prefix,
            "product_hint": self.product_hint,
            "device_family": self.device_family,
            "device_class": self.device_class,
            "vendor_confidence": self.vendor_confidence,
            "reference_updated_at": self.reference_updated_at,
            "mac_is_randomized": self.mac_is_randomized,
            "mac_identity_kind": self.mac_identity_kind,
            "mac_reason": self.mac_reason,
        }


_payload: dict[str, Any] | None = None
_mac_by_key: dict[tuple[str, int], dict[str, Any]] = {}
_ble_company_ids: dict[int, dict[str, Any]] = {}
_ssid_patterns: list[dict[str, Any]] = []


def _load() -> dict[str, Any]:
    global _payload, _mac_by_key, _ble_company_ids, _ssid_patterns
    if _payload is not None:
        return _payload
    if REFERENCE_PATH.exists():
        _payload = json.loads(REFERENCE_PATH.read_text())
    else:
        _payload = {
            "schema_version": 0,
            "generated_at": None,
            "sources": {},
            "source_entry_counts": {},
            "mac_prefixes": [],
            "ble_company_ids": {},
            "ssid_patterns": [],
        }
    _mac_by_key = {}
    for item in _payload.get("mac_prefixes", []):
        try:
            bits = int(item.get("bits"))
        except Exception:
            continue
        prefix = str(item.get("prefix") or "").upper()
        if prefix:
            _mac_by_key[(prefix, bits)] = item
    _ble_company_ids = {
        int(k): v for k, v in (_payload.get("ble_company_ids") or {}).items()
        if str(k).isdigit()
    }
    _ssid_patterns = [
        p for p in (_payload.get("ssid_patterns") or [])
        if p.get("pattern")
    ]
    return _payload


def reload_reference() -> None:
    """Clear the in-process cache; intended for tests/dev refreshes."""
    global _payload, _mac_by_key, _ble_company_ids, _ssid_patterns
    _payload = None
    _mac_by_key = {}
    _ble_company_ids = {}
    _ssid_patterns = []


def _hex_mac(mac: str | None) -> str | None:
    hex_only = re.sub(r"[^0-9A-Fa-f]", "", mac or "").upper()
    if len(hex_only) < 12:
        return None
    return hex_only[:12]


def _prefix_for_bits(hex_mac: str, bits: int) -> str:
    return hex_mac[: (bits + 3) // 4]


def _format_prefix(hex_mac: str, bits: int | None = 24) -> str | None:
    if not hex_mac:
        return None
    nibbles = (int(bits or 24) + 3) // 4
    prefix = hex_mac[:nibbles]
    if len(prefix) < 6:
        return None
    parts = [prefix[i:i + 2] for i in range(0, min(len(prefix), 6), 2)]
    suffix = prefix[6:]
    return ":".join(parts) + (f"/{bits}" if suffix or bits != 24 else "")


def _display_vendor(entry: dict[str, Any]) -> tuple[str | None, str | None]:
    short = str(entry.get("vendor_short") or "").strip()
    long = str(entry.get("vendor_long") or "").strip()
    if re.fullmatch(r"[0-9A-Fa-f:./-]+", short):
        short = ""
    return short or long or None, long or short or None


def _confidence(entry: dict[str, Any]) -> float:
    assignment = str(entry.get("assignment_type") or "")
    bits = int(entry.get("bits") or 24)
    if assignment == "CID":
        return 0.45
    if bits >= 36:
        return 0.92
    if bits >= 28:
        return 0.88
    return 0.82


def resolve_mac(mac: str | None, *, source: str | None = None, ble_addr_type: int | None = None) -> MacResolution:
    _load()
    hex_mac = _hex_mac(mac)
    source_l = (source or "").lower()
    if not hex_mac:
        return MacResolution(
            vendor_short=None, vendor_long=None, vendor_aliases=[], vendor_source=None,
            assignment_type=None, prefix_bits=None, oui_prefix=None, product_hint=None,
            device_family=None, device_class=None, vendor_confidence=0.0,
            reference_updated_at=_payload.get("generated_at") if _payload else None,
            mac_is_randomized=False, mac_identity_kind="unknown", mac_reason="missing_mac",
        )

    if source_l.startswith("ble") and ble_addr_type == 2:
        return _randomized_resolution(hex_mac, "ble_rpa", "ble_addr_type_rpa")
    if source_l.startswith("ble") and ble_addr_type in (1, 3):
        return _randomized_resolution(hex_mac, "ble_random_static", "ble_random_address_type")
    if _legacy_is_random_mac(mac):
        return _randomized_resolution(hex_mac, "randomized", "locally_administered_bit")

    for bits in (36, 28, 24):
        hit = _mac_by_key.get((_prefix_for_bits(hex_mac, bits), bits))
        if hit:
            short, long = _display_vendor(hit)
            aliases = sorted({str(a) for a in (hit.get("vendor_aliases") or []) if a})
            return MacResolution(
                vendor_short=short,
                vendor_long=long,
                vendor_aliases=aliases[:8],
                vendor_source=str(hit.get("vendor_source") or ""),
                assignment_type=str(hit.get("assignment_type") or ""),
                prefix_bits=bits,
                oui_prefix=_format_prefix(hex_mac, bits),
                product_hint=hit.get("product_hint"),
                device_family=hit.get("device_family"),
                device_class=hit.get("device_class"),
                vendor_confidence=_confidence(hit),
                reference_updated_at=_payload.get("generated_at") if _payload else None,
                mac_is_randomized=False,
                mac_identity_kind="public_oui",
                mac_reason="public_oui",
            )

    return MacResolution(
        vendor_short=None, vendor_long=None, vendor_aliases=[], vendor_source=None,
        assignment_type=None, prefix_bits=None, oui_prefix=_format_prefix(hex_mac, 24),
        product_hint=None, device_family=None, device_class=None, vendor_confidence=0.0,
        reference_updated_at=_payload.get("generated_at") if _payload else None,
        mac_is_randomized=False, mac_identity_kind="unknown", mac_reason="unassigned_or_unknown_prefix",
    )


def _randomized_resolution(hex_mac: str, kind: str, reason: str) -> MacResolution:
    return MacResolution(
        vendor_short=None,
        vendor_long=None,
        vendor_aliases=[],
        vendor_source="randomized_mac",
        assignment_type=None,
        prefix_bits=None,
        oui_prefix=None,
        product_hint=None,
        device_family=None,
        device_class=None,
        vendor_confidence=0.0,
        reference_updated_at=_payload.get("generated_at") if _payload else None,
        mac_is_randomized=True,
        mac_identity_kind=kind,
        mac_reason=reason,
    )


def lookup_ble_company(company_id: int | None) -> dict[str, Any] | None:
    if company_id is None:
        return None
    _load()
    try:
        code = int(company_id)
    except Exception:
        return None
    hit = _ble_company_ids.get(code)
    if not hit:
        return None
    return {
        "code": code,
        "name": hit.get("name"),
        "source": hit.get("source") or "bluetooth_sig",
        "reference_updated_at": _payload.get("generated_at") if _payload else None,
    }


def source_details(source_ids: str | list[str] | tuple[str, ...] | set[str] | None) -> list[dict[str, Any]]:
    """Resolve local reference source ids into UI-safe provenance records."""
    payload = _load()
    if not source_ids:
        return []
    if isinstance(source_ids, str):
        ids = [part.strip() for part in re.split(r"[+,]", source_ids) if part.strip()]
    else:
        ids = [str(part).strip() for part in source_ids if str(part).strip()]
    sources = payload.get("sources", {}) or {}
    result: list[dict[str, Any]] = []
    seen: set[str] = set()
    for source_id in ids:
        if source_id in seen:
            continue
        seen.add(source_id)
        meta = sources.get(source_id) or {}
        result.append({
            "id": source_id,
            "label": SOURCE_LABELS.get(source_id, source_id.replace("_", " ").title()),
            "url": meta.get("url") or STATIC_SOURCE_URLS.get(source_id),
            "sha256": meta.get("sha256"),
            "bytes": meta.get("bytes"),
            "artifact_generated_at": payload.get("generated_at"),
        })
    return result


def ssid_pattern_hints(ssids: list[str] | None, ssid: str | None = None) -> list[dict[str, Any]]:
    _load()
    values = [s for s in [ssid, *(ssids or [])] if s and s != "(broadcast)"]
    hints: list[dict[str, Any]] = []
    seen: set[str] = set()
    for value in values:
        value_l = value.lower()
        for spec in _ssid_patterns:
            pattern = str(spec.get("pattern") or "").lower()
            if not pattern or not fnmatchcase(value_l, pattern):
                continue
            label = str(spec.get("label") or pattern)
            key = f"{label}:{value_l}"
            if key in seen:
                continue
            hint = dict(spec)
            hint["matched_ssid"] = value
            hint["source"] = "operator_ssid_override" if "TeamCharityCase" in label else "ssid_pattern"
            hints.append(hint)
            seen.add(key)
    return hints


def reference_status(recent_detections: list[Any] | None = None) -> dict[str, Any]:
    payload = _load()
    recent = list(recent_detections or [])
    enriched = 0
    randomized = 0
    unknown = 0
    for det in recent:
        mac = getattr(det, "bssid", None)
        if not mac:
            continue
        res = resolve_mac(mac, source=getattr(det, "source", None), ble_addr_type=getattr(det, "ble_addr_type", None))
        if res.mac_is_randomized:
            randomized += 1
        elif res.vendor_short or res.vendor_long:
            enriched += 1
        else:
            unknown += 1
    total_mac = enriched + randomized + unknown
    return {
        "schema_version": payload.get("schema_version"),
        "generated_at": payload.get("generated_at"),
        "reference_age_s": (
            round(time.time() - _parse_epoch(payload.get("generated_at")), 1)
            if payload.get("generated_at") else None
        ),
        "sources": payload.get("sources", {}),
        "source_entry_counts": payload.get("source_entry_counts", {}),
        "mac_prefix_count": len(payload.get("mac_prefixes", [])),
        "ble_company_count": len(payload.get("ble_company_ids", {})),
        "ssid_pattern_count": len(payload.get("ssid_patterns", [])),
        "recent_mac_total": total_mac,
        "recent_mac_enriched": enriched,
        "recent_mac_randomized": randomized,
        "recent_mac_unknown": unknown,
        "recent_mac_enriched_pct": round((enriched / total_mac) * 100.0, 1) if total_mac else None,
    }


def _parse_epoch(value: str | None) -> float:
    if not value:
        return time.time()
    try:
        from datetime import datetime

        return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp()
    except Exception:
        return time.time()
