#include "unity.h"

void setUp(void) {}
void tearDown(void) {}

void test_initial_probability(void);
void test_single_ble_update(void);
void test_wifi_ssid_low_confidence(void);
void test_multi_source_boost(void);
void test_time_decay(void);
void test_prune(void);

void test_parse_valid_payload(void);
void test_parse_zero_coords(void);
void test_parse_short_payload(void);
void test_parse_wrong_oui(void);

void test_parse_basic_id(void);
void test_parse_location(void);
void test_parse_system(void);
void test_parse_operator_id(void);
void test_parse_self_id(void);
void test_parse_message_pack(void);
void test_accuracy_code_to_meters(void);
void test_invalid_location_zero(void);
void test_state_to_detection(void);

void test_dji_match(void);
void test_tello_match(void);
void test_case_insensitive(void);
void test_no_match(void);
void test_hover_air(void);
void test_generic_drone(void);
void test_fof_drone_test_ssids(void);
void test_budget_drone_prefixes(void);
void test_all_patterns_valid(void);
void test_null_ssid(void);
void test_probe_broadcasts_still_drop(void);
void test_hard_probe_matches_keep_elevated_confidence(void);
void test_generic_targeted_probes_are_not_low_value_dropped(void);
void test_fof_drone_ssids_are_notable_but_ambient_fof_is_not(void);
void test_probe_rate_aux_changes_when_identity_changes(void);
void test_queue_shedding_prefers_diagnostic_sources_first(void);
void test_ap_inventory_dedupe_key_uses_bssid(void);
void test_calibration_ble_uuid_is_recognized_and_kept(void);
void test_dedupe_key_groups_probe_ie_hash_across_rotated_macs(void);
void test_dedupe_key_changes_across_time_bucket(void);
void test_ble_fingerprint_dedupe_keeps_mac_in_identity(void);
void test_ble_fingerprint_meta_name_is_case_insensitive(void);
void test_ble_fingerprint_meta_rayban_uuid_is_human_evidence(void);
void test_ble_fingerprint_meta_service_uuid_keeps_exact_reason(void);
void test_ble_fingerprint_meta_feb8_is_high_recall_glasses(void);
void test_ble_fingerprint_luxottica_cid_is_meta_glasses(void);
void test_hidden_camera_ble_is_priority_not_low_value(void);
void test_priority_ble_fingerprint_is_not_shed_under_pressure(void);
void test_priority_ble_fingerprint_uses_short_reemit_window(void);
void test_scan_profiles_assign_slot_roles_and_calibration_override(void);
void test_scan_profile_source_gates_normal_lanes(void);
void test_ble_meta_reacquire_triggers_when_stale_and_advancing(void);
void test_ble_meta_reacquire_blocks_calibration_or_ota(void);
void test_ble_meta_reacquire_requires_scan_sync_and_adv_delta(void);
void test_badge_repeated_drone_stays_single_entity(void);
void test_badge_meta_plus_drone_raises_score(void);
void test_badge_meta_stays_active_for_live_window(void);
void test_badge_meta_last_seen_memory_outlives_active_window(void);
void test_badge_meta_count_drops_after_live_window(void);
void test_badge_meta_memory_expires_after_fifteen_minutes(void);
void test_badge_drone_priority_beats_close_glasses(void);
void test_badge_close_airtag_drives_privacy_alert(void);
void test_badge_close_airtag_survives_when_generic_wifi_noise_is_ignored(void);
void test_badge_repeated_meta_groups_seen_count_and_best_rssi(void);
void test_badge_meta_variants_merge_into_one_display_entity(void);
void test_badge_strong_unknown_ble_is_suppressed(void);
void test_badge_structured_nearby_ble_is_suppressed(void);
void test_badge_far_unknown_ble_does_not_flood_display(void);
void test_badge_unknown_ble_is_suppressed_behind_wifi_anomaly(void);
void test_badge_glasses_rank_above_wifi_anomaly_even_when_stale(void);
void test_badge_meta_sorts_above_louder_generic_ble(void);
void test_badge_score_fades_after_activity_stales(void);
void test_badge_drone_memory_expires_after_demo_window(void);
void test_badge_wifi_anomaly_memory_outlives_active_window(void);
void test_badge_multiple_drones_raise_score(void);
void test_badge_wifi_noise_is_ignored(void);
void test_badge_labels_are_lcd_safe_friendly_names(void);
void test_badge_drone_ssid_label_keeps_detail(void);
void test_badge_fof_drone_ssid_is_not_suppressed(void);
void test_badge_meta_structured_evidence_beats_tracker_label(void);
void test_badge_meta_uuid_detail_is_human_not_raw_hex(void);
void test_badge_remote_id_without_human_fields_hides_raw_hex_detail(void);
void test_badge_generic_nearby_ble_is_not_a_display_row(void);
void test_badge_tracker_label_names_airtag(void);
void test_badge_far_airtag_is_hidden_unless_close(void);
void test_badge_remote_id_with_human_evidence_ranks_first(void);
void test_badge_notable_ssid_ranks_above_flock_and_glasses(void);
void test_badge_notable_ssid_suffixes_group_for_readability(void);
void test_badge_teamcharitycase_ssid_is_suppressed(void);
void test_badge_plain_fof_ssid_is_suppressed_as_ambient(void);
void test_badge_flock_ble_name_produces_flock_camera(void);
void test_badge_meta_rayban_category_is_glass(void);
void test_badge_skimmer_names_produce_skim_rows(void);
void test_badge_privacy_pack_maps_camera_lock_hid_labels(void);
void test_badge_venue_beacons_aggregate_instead_of_flooding(void);
void test_badge_generic_apple_continuity_does_not_become_lcd_alert(void);
void test_badge_close_findmy_tracker_promotes_tracker_near(void);
void test_badge_generic_drone_without_evidence_is_hidden(void);
void test_badge_deauth_status_event_gets_wifi_label(void);
void test_badge_disassoc_status_event_gets_specific_wifi_label(void);
void test_badge_strong_normal_wifi_assoc_is_ignored(void);
void test_badge_status_meta_evidence_is_diagnostic_only(void);
void test_badge_status_wifi_drone_ssid_creates_ssid_entity(void);
void test_badge_wifi_drone_ssid_from_two_slots_merges_entity(void);
void test_badge_status_and_live_wifi_drone_ssid_merge_entity(void);
void test_badge_status_wifi_drone_detail_names_network(void);
void test_badge_remote_id_title_helper_says_drone_near(void);
void test_badge_remote_id_title_helper_counts_multiple_drones(void);
void test_badge_drone_evidence_count_includes_rid_and_ssid(void);
void test_badge_lower_lane_hides_single_drone_evidence(void);
void test_badge_lower_lane_shows_multiple_drone_evidence(void);
void test_badge_drone_evidence_count_includes_two_rid_and_ssid(void);
void test_badge_display_lane_splits_ble_and_wifi_items(void);
void test_badge_drone_evidence_count_excludes_stale_ssid(void);
void test_badge_view_key_uses_remote_id_display_id(void);
void test_badge_meta_glasses_title_count_and_display_ids(void);
void test_badge_meta_count_ignores_scanner_seen_group_count(void);
void test_badge_meta_top_rotation_uses_strong_identities(void);
void test_badge_meta_top_rotation_weak_presence_is_single(void);
void test_badge_lower_meta_evidence_hidden_when_top_meta_active(void);
void test_badge_meta_same_fingerprint_from_two_scanners_counts_once(void);
void test_badge_meta_rotated_mac_same_fingerprint_counts_once(void);
void test_badge_two_weak_meta_signals_count_as_single_presence(void);
void test_badge_strong_meta_plus_weak_duplicate_counts_once(void);
void test_badge_weak_meta_presence_expires_after_live_window(void);
void test_badge_three_meta_fingerprints_count_three(void);
void test_badge_meta_view_key_uses_display_id_for_distinct_glasses(void);
void test_badge_meta_proximity_percent_tracks_rssi(void);
void test_badge_meta_signal_percent_uses_latest_rssi_and_decays(void);
void test_badge_meta_signal_percent_calibrates_ice_to_fire_rssi(void);
void test_badge_meta_heat_ignores_count_boost(void);
void test_badge_top_count_color_follows_meta_heat(void);
void test_badge_top_count_color_follows_drone_count_heat(void);
void test_badge_top_detail_formats_compact_large_text(void);
void test_badge_top_detail_large_text_rejects_long_rows(void);
void test_badge_display_policy_json_round_trips_defaults(void);
void test_badge_display_policy_rejects_invalid_lane(void);
void test_badge_display_policy_disabled_beacon_suppresses_normal_detection(void);
void test_badge_display_policy_drone_breaks_through_disabled_filter(void);
void test_badge_display_policy_close_tracker_breaks_through_disabled_filter(void);
void test_badge_heat_color_runs_ice_to_fire(void);
void test_badge_heat_percent_combines_proximity_and_count(void);
void test_badge_heat_percent_no_live_count_means_no_bar(void);
void test_badge_marquee_offset_advances_for_long_lower_lane_text(void);
void test_badge_fast_marquee_offset_is_twenty_percent_faster(void);
void test_badge_viewed_remote_id_suppresses_only_same_drone(void);
void test_badge_viewed_single_remote_id_leaves_no_unviewed_drone(void);
void test_badge_view_key_non_rid_uses_category_title_detail(void);
void test_badge_drone_ssid_uses_short_display_lifetime(void);
void test_badge_remote_id_keeps_longer_drone_lifetime(void);
void test_badge_remote_id_stale_second_drops_from_active_count(void);
void test_badge_status_ssid_freshness_requires_recent_nonempty_value(void);
void test_badge_status_notable_wifi_ssid_creates_wifi_entity(void);
void test_badge_status_generic_noise_remains_suppressed(void);
void test_badge_drone_snapshot_preserves_drone_and_operator_coords(void);
void test_badge_default_network_is_usb_only(void);
void test_badge_network_ttl_defaults_and_off(void);
void test_badge_network_sessions_are_explicitly_allowed(void);
void test_badge_post_ota_network_hold_defaults_and_off(void);
void test_badge_pending_verify_crash_forces_rollback(void);
void test_badge_expected_software_reset_does_not_increment_crash_count(void);
void test_badge_unplanned_software_reset_counts_as_crash(void);
void test_badge_validated_crash_loop_enters_safe_mode(void);
void test_badge_health_gate_requires_display_usb_scanner_and_heap(void);
void test_badge_usb_recovery_waits_through_boot_grace(void);
void test_badge_usb_recovery_ignores_safe_mode(void);
void test_badge_usb_recovery_triggers_when_control_never_starts(void);
void test_badge_usb_recovery_triggers_when_control_stale(void);
void test_badge_usb_recovery_stays_clear_when_control_fresh(void);
void test_time_message_validity_tracks_ok_flag_and_epoch(void);
void test_backend_epoch_resteers_only_when_drift_exceeds_threshold(void);
void test_sntp_synced_uplink_ignores_backend_overwrite(void);
void test_stale_timeout_marks_scanner_state_stale(void);
void test_firmware_update_protocol_message_names_are_stable(void);
void test_firmware_update_protocol_carries_crc_and_target_metadata(void);
void test_ota_protocol_carries_session_id_for_exact_ack_matching(void);
void test_badge_uart_ota_uses_fast_bounded_chunks(void);
void test_badge_relay_timeout_policy_is_bounded(void);

void test_clean_boot_keeps_counter_carried_no_action(void);
void test_brownout_does_not_count_as_crash(void);
void test_panic_increments_counter(void);
void test_panic_on_pending_verify_forces_rollback_immediately(void);
void test_task_wdt_on_pending_verify_forces_rollback(void);
void test_int_wdt_on_pending_verify_forces_rollback(void);
void test_three_panics_on_validated_marks_crash_loop(void);
void test_validated_crash_loop_enters_safe_uart_recovery(void);
void test_well_above_threshold_still_marks_crash_loop_not_rollback(void);
void test_pending_verify_takes_priority_over_threshold(void);
void test_clean_boot_does_not_lower_existing_count(void);

void test_decide_skips_when_wifi_down(void);
void test_decide_skips_when_relay_active(void);
void test_decide_skips_when_heap_too_low(void);
void test_decide_allows_first_check_when_age_zero(void);
void test_decide_skips_when_too_recent(void);
void test_decide_proceeds_at_interval_boundary(void);
void test_decide_proceeds_long_after_interval(void);
void test_versions_match_returns_false(void);
void test_versions_differ_returns_true(void);
void test_remote_unknown_does_not_trigger_update(void);
void test_remote_empty_does_not_trigger_update(void);
void test_local_empty_takes_remote(void);
void test_versions_differ_across_naming_schemes(void);

int main(void)
{
    UNITY_BEGIN();

    RUN_TEST(test_initial_probability);
    RUN_TEST(test_single_ble_update);
    RUN_TEST(test_wifi_ssid_low_confidence);
    RUN_TEST(test_multi_source_boost);
    RUN_TEST(test_time_decay);
    RUN_TEST(test_prune);

    RUN_TEST(test_parse_valid_payload);
    RUN_TEST(test_parse_zero_coords);
    RUN_TEST(test_parse_short_payload);
    RUN_TEST(test_parse_wrong_oui);

    RUN_TEST(test_parse_basic_id);
    RUN_TEST(test_parse_location);
    RUN_TEST(test_parse_system);
    RUN_TEST(test_parse_operator_id);
    RUN_TEST(test_parse_self_id);
    RUN_TEST(test_parse_message_pack);
    RUN_TEST(test_accuracy_code_to_meters);
    RUN_TEST(test_invalid_location_zero);
    RUN_TEST(test_state_to_detection);

    RUN_TEST(test_dji_match);
    RUN_TEST(test_tello_match);
    RUN_TEST(test_case_insensitive);
    RUN_TEST(test_no_match);
    RUN_TEST(test_hover_air);
    RUN_TEST(test_generic_drone);
    RUN_TEST(test_fof_drone_test_ssids);
    RUN_TEST(test_budget_drone_prefixes);
    RUN_TEST(test_all_patterns_valid);
    RUN_TEST(test_null_ssid);
    RUN_TEST(test_probe_broadcasts_still_drop);
    RUN_TEST(test_hard_probe_matches_keep_elevated_confidence);
    RUN_TEST(test_generic_targeted_probes_are_not_low_value_dropped);
    RUN_TEST(test_fof_drone_ssids_are_notable_but_ambient_fof_is_not);
    RUN_TEST(test_probe_rate_aux_changes_when_identity_changes);
    RUN_TEST(test_queue_shedding_prefers_diagnostic_sources_first);
    RUN_TEST(test_ap_inventory_dedupe_key_uses_bssid);
    RUN_TEST(test_calibration_ble_uuid_is_recognized_and_kept);
    RUN_TEST(test_dedupe_key_groups_probe_ie_hash_across_rotated_macs);
    RUN_TEST(test_dedupe_key_changes_across_time_bucket);
    RUN_TEST(test_ble_fingerprint_dedupe_keeps_mac_in_identity);
    RUN_TEST(test_ble_fingerprint_meta_name_is_case_insensitive);
    RUN_TEST(test_ble_fingerprint_meta_rayban_uuid_is_human_evidence);
    RUN_TEST(test_ble_fingerprint_meta_service_uuid_keeps_exact_reason);
    RUN_TEST(test_ble_fingerprint_meta_feb8_is_high_recall_glasses);
    RUN_TEST(test_ble_fingerprint_luxottica_cid_is_meta_glasses);
    RUN_TEST(test_hidden_camera_ble_is_priority_not_low_value);
    RUN_TEST(test_priority_ble_fingerprint_is_not_shed_under_pressure);
    RUN_TEST(test_priority_ble_fingerprint_uses_short_reemit_window);
    RUN_TEST(test_scan_profiles_assign_slot_roles_and_calibration_override);
    RUN_TEST(test_scan_profile_source_gates_normal_lanes);
    RUN_TEST(test_ble_meta_reacquire_triggers_when_stale_and_advancing);
    RUN_TEST(test_ble_meta_reacquire_blocks_calibration_or_ota);
    RUN_TEST(test_ble_meta_reacquire_requires_scan_sync_and_adv_delta);
    RUN_TEST(test_badge_repeated_drone_stays_single_entity);
    RUN_TEST(test_badge_meta_plus_drone_raises_score);
    RUN_TEST(test_badge_meta_stays_active_for_live_window);
    RUN_TEST(test_badge_meta_last_seen_memory_outlives_active_window);
    RUN_TEST(test_badge_meta_count_drops_after_live_window);
    RUN_TEST(test_badge_meta_memory_expires_after_fifteen_minutes);
    RUN_TEST(test_badge_drone_priority_beats_close_glasses);
    RUN_TEST(test_badge_close_airtag_drives_privacy_alert);
    RUN_TEST(test_badge_close_airtag_survives_when_generic_wifi_noise_is_ignored);
    RUN_TEST(test_badge_repeated_meta_groups_seen_count_and_best_rssi);
    RUN_TEST(test_badge_meta_variants_merge_into_one_display_entity);
    RUN_TEST(test_badge_strong_unknown_ble_is_suppressed);
    RUN_TEST(test_badge_structured_nearby_ble_is_suppressed);
    RUN_TEST(test_badge_far_unknown_ble_does_not_flood_display);
    RUN_TEST(test_badge_unknown_ble_is_suppressed_behind_wifi_anomaly);
    RUN_TEST(test_badge_glasses_rank_above_wifi_anomaly_even_when_stale);
    RUN_TEST(test_badge_meta_sorts_above_louder_generic_ble);
    RUN_TEST(test_badge_score_fades_after_activity_stales);
    RUN_TEST(test_badge_drone_memory_expires_after_demo_window);
    RUN_TEST(test_badge_wifi_anomaly_memory_outlives_active_window);
    RUN_TEST(test_badge_multiple_drones_raise_score);
    RUN_TEST(test_badge_wifi_noise_is_ignored);
    RUN_TEST(test_badge_labels_are_lcd_safe_friendly_names);
    RUN_TEST(test_badge_drone_ssid_label_keeps_detail);
    RUN_TEST(test_badge_fof_drone_ssid_is_not_suppressed);
    RUN_TEST(test_badge_meta_structured_evidence_beats_tracker_label);
    RUN_TEST(test_badge_meta_uuid_detail_is_human_not_raw_hex);
    RUN_TEST(test_badge_remote_id_without_human_fields_hides_raw_hex_detail);
    RUN_TEST(test_badge_generic_nearby_ble_is_not_a_display_row);
    RUN_TEST(test_badge_tracker_label_names_airtag);
    RUN_TEST(test_badge_far_airtag_is_hidden_unless_close);
    RUN_TEST(test_badge_remote_id_with_human_evidence_ranks_first);
    RUN_TEST(test_badge_notable_ssid_ranks_above_flock_and_glasses);
    RUN_TEST(test_badge_notable_ssid_suffixes_group_for_readability);
    RUN_TEST(test_badge_teamcharitycase_ssid_is_suppressed);
    RUN_TEST(test_badge_plain_fof_ssid_is_suppressed_as_ambient);
    RUN_TEST(test_badge_flock_ble_name_produces_flock_camera);
    RUN_TEST(test_badge_meta_rayban_category_is_glass);
    RUN_TEST(test_badge_skimmer_names_produce_skim_rows);
    RUN_TEST(test_badge_privacy_pack_maps_camera_lock_hid_labels);
    RUN_TEST(test_badge_venue_beacons_aggregate_instead_of_flooding);
    RUN_TEST(test_badge_generic_apple_continuity_does_not_become_lcd_alert);
    RUN_TEST(test_badge_close_findmy_tracker_promotes_tracker_near);
    RUN_TEST(test_badge_generic_drone_without_evidence_is_hidden);
    RUN_TEST(test_badge_deauth_status_event_gets_wifi_label);
    RUN_TEST(test_badge_disassoc_status_event_gets_specific_wifi_label);
    RUN_TEST(test_badge_strong_normal_wifi_assoc_is_ignored);
    RUN_TEST(test_badge_status_meta_evidence_is_diagnostic_only);
    RUN_TEST(test_badge_status_wifi_drone_ssid_creates_ssid_entity);
    RUN_TEST(test_badge_wifi_drone_ssid_from_two_slots_merges_entity);
    RUN_TEST(test_badge_status_and_live_wifi_drone_ssid_merge_entity);
    RUN_TEST(test_badge_status_wifi_drone_detail_names_network);
    RUN_TEST(test_badge_remote_id_title_helper_says_drone_near);
    RUN_TEST(test_badge_remote_id_title_helper_counts_multiple_drones);
    RUN_TEST(test_badge_drone_evidence_count_includes_rid_and_ssid);
    RUN_TEST(test_badge_lower_lane_hides_single_drone_evidence);
    RUN_TEST(test_badge_lower_lane_shows_multiple_drone_evidence);
    RUN_TEST(test_badge_drone_evidence_count_includes_two_rid_and_ssid);
    RUN_TEST(test_badge_display_lane_splits_ble_and_wifi_items);
    RUN_TEST(test_badge_drone_evidence_count_excludes_stale_ssid);
    RUN_TEST(test_badge_view_key_uses_remote_id_display_id);
    RUN_TEST(test_badge_meta_glasses_title_count_and_display_ids);
    RUN_TEST(test_badge_meta_count_ignores_scanner_seen_group_count);
    RUN_TEST(test_badge_meta_top_rotation_uses_strong_identities);
    RUN_TEST(test_badge_meta_top_rotation_weak_presence_is_single);
    RUN_TEST(test_badge_lower_meta_evidence_hidden_when_top_meta_active);
    RUN_TEST(test_badge_meta_same_fingerprint_from_two_scanners_counts_once);
    RUN_TEST(test_badge_meta_rotated_mac_same_fingerprint_counts_once);
    RUN_TEST(test_badge_two_weak_meta_signals_count_as_single_presence);
    RUN_TEST(test_badge_strong_meta_plus_weak_duplicate_counts_once);
    RUN_TEST(test_badge_weak_meta_presence_expires_after_live_window);
    RUN_TEST(test_badge_three_meta_fingerprints_count_three);
    RUN_TEST(test_badge_meta_view_key_uses_display_id_for_distinct_glasses);
    RUN_TEST(test_badge_meta_proximity_percent_tracks_rssi);
    RUN_TEST(test_badge_meta_signal_percent_uses_latest_rssi_and_decays);
    RUN_TEST(test_badge_meta_signal_percent_calibrates_ice_to_fire_rssi);
    RUN_TEST(test_badge_meta_heat_ignores_count_boost);
    RUN_TEST(test_badge_top_count_color_follows_meta_heat);
    RUN_TEST(test_badge_top_count_color_follows_drone_count_heat);
    RUN_TEST(test_badge_top_detail_formats_compact_large_text);
    RUN_TEST(test_badge_top_detail_large_text_rejects_long_rows);
    RUN_TEST(test_badge_display_policy_json_round_trips_defaults);
    RUN_TEST(test_badge_display_policy_rejects_invalid_lane);
    RUN_TEST(test_badge_display_policy_disabled_beacon_suppresses_normal_detection);
    RUN_TEST(test_badge_display_policy_drone_breaks_through_disabled_filter);
    RUN_TEST(test_badge_display_policy_close_tracker_breaks_through_disabled_filter);
    RUN_TEST(test_badge_heat_color_runs_ice_to_fire);
    RUN_TEST(test_badge_heat_percent_combines_proximity_and_count);
    RUN_TEST(test_badge_heat_percent_no_live_count_means_no_bar);
    RUN_TEST(test_badge_marquee_offset_advances_for_long_lower_lane_text);
    RUN_TEST(test_badge_fast_marquee_offset_is_twenty_percent_faster);
    RUN_TEST(test_badge_viewed_remote_id_suppresses_only_same_drone);
    RUN_TEST(test_badge_viewed_single_remote_id_leaves_no_unviewed_drone);
    RUN_TEST(test_badge_view_key_non_rid_uses_category_title_detail);
    RUN_TEST(test_badge_drone_ssid_uses_short_display_lifetime);
    RUN_TEST(test_badge_remote_id_keeps_longer_drone_lifetime);
    RUN_TEST(test_badge_remote_id_stale_second_drops_from_active_count);
    RUN_TEST(test_badge_status_ssid_freshness_requires_recent_nonempty_value);
    RUN_TEST(test_badge_status_notable_wifi_ssid_creates_wifi_entity);
    RUN_TEST(test_badge_status_generic_noise_remains_suppressed);
    RUN_TEST(test_badge_drone_snapshot_preserves_drone_and_operator_coords);
    RUN_TEST(test_badge_default_network_is_usb_only);
    RUN_TEST(test_badge_network_ttl_defaults_and_off);
    RUN_TEST(test_badge_network_sessions_are_explicitly_allowed);
    RUN_TEST(test_badge_post_ota_network_hold_defaults_and_off);
    RUN_TEST(test_badge_pending_verify_crash_forces_rollback);
    RUN_TEST(test_badge_expected_software_reset_does_not_increment_crash_count);
    RUN_TEST(test_badge_unplanned_software_reset_counts_as_crash);
    RUN_TEST(test_badge_validated_crash_loop_enters_safe_mode);
    RUN_TEST(test_badge_health_gate_requires_display_usb_scanner_and_heap);
    RUN_TEST(test_badge_usb_recovery_waits_through_boot_grace);
    RUN_TEST(test_badge_usb_recovery_ignores_safe_mode);
    RUN_TEST(test_badge_usb_recovery_triggers_when_control_never_starts);
    RUN_TEST(test_badge_usb_recovery_triggers_when_control_stale);
    RUN_TEST(test_badge_usb_recovery_stays_clear_when_control_fresh);
    RUN_TEST(test_time_message_validity_tracks_ok_flag_and_epoch);
    RUN_TEST(test_backend_epoch_resteers_only_when_drift_exceeds_threshold);
    RUN_TEST(test_sntp_synced_uplink_ignores_backend_overwrite);
    RUN_TEST(test_stale_timeout_marks_scanner_state_stale);
    RUN_TEST(test_firmware_update_protocol_message_names_are_stable);
    RUN_TEST(test_firmware_update_protocol_carries_crc_and_target_metadata);
    RUN_TEST(test_ota_protocol_carries_session_id_for_exact_ack_matching);
    RUN_TEST(test_badge_uart_ota_uses_fast_bounded_chunks);
    RUN_TEST(test_badge_relay_timeout_policy_is_bounded);

    RUN_TEST(test_clean_boot_keeps_counter_carried_no_action);
    RUN_TEST(test_brownout_does_not_count_as_crash);
    RUN_TEST(test_panic_increments_counter);
    RUN_TEST(test_panic_on_pending_verify_forces_rollback_immediately);
    RUN_TEST(test_task_wdt_on_pending_verify_forces_rollback);
    RUN_TEST(test_int_wdt_on_pending_verify_forces_rollback);
    RUN_TEST(test_three_panics_on_validated_marks_crash_loop);
    RUN_TEST(test_validated_crash_loop_enters_safe_uart_recovery);
    RUN_TEST(test_well_above_threshold_still_marks_crash_loop_not_rollback);
    RUN_TEST(test_pending_verify_takes_priority_over_threshold);
    RUN_TEST(test_clean_boot_does_not_lower_existing_count);

    RUN_TEST(test_decide_skips_when_wifi_down);
    RUN_TEST(test_decide_skips_when_relay_active);
    RUN_TEST(test_decide_skips_when_heap_too_low);
    RUN_TEST(test_decide_allows_first_check_when_age_zero);
    RUN_TEST(test_decide_skips_when_too_recent);
    RUN_TEST(test_decide_proceeds_at_interval_boundary);
    RUN_TEST(test_decide_proceeds_long_after_interval);
    RUN_TEST(test_versions_match_returns_false);
    RUN_TEST(test_versions_differ_returns_true);
    RUN_TEST(test_remote_unknown_does_not_trigger_update);
    RUN_TEST(test_remote_empty_does_not_trigger_update);
    RUN_TEST(test_local_empty_takes_remote);
    RUN_TEST(test_versions_differ_across_naming_schemes);

    return UNITY_END();
}
