package com.friendorfoe.presentation.util

/**
 * Resolves airline names from ICAO 3-letter callsign prefixes.
 *
 * Ported from backend enrichment service (app/services/enrichment.py).
 */
object AirlineLookup {
    data class AirlineInfo(val name: String, val iataCode: String)

    private val PREFIXES = mapOf(
        "AAL" to AirlineInfo("American Airlines", "AA"),
        "UAL" to AirlineInfo("United Airlines", "UA"),
        "DAL" to AirlineInfo("Delta Air Lines", "DL"),
        "SWA" to AirlineInfo("Southwest Airlines", "WN"),
        "JBU" to AirlineInfo("JetBlue Airways", "B6"),
        "SKW" to AirlineInfo("SkyWest Airlines", "OO"),
        "ASA" to AirlineInfo("Alaska Airlines", "AS"),
        "NKS" to AirlineInfo("Spirit Airlines", "NK"),
        "FFT" to AirlineInfo("Frontier Airlines", "F9"),
        "RPA" to AirlineInfo("Republic Airways", "YX"),
        "ENY" to AirlineInfo("Envoy Air", "MQ"),
        "BAW" to AirlineInfo("British Airways", "BA"),
        "DLH" to AirlineInfo("Lufthansa", "LH"),
        "AFR" to AirlineInfo("Air France", "AF"),
        "KLM" to AirlineInfo("KLM Royal Dutch", "KL"),
        "EZY" to AirlineInfo("easyJet", "U2"),
        "RYR" to AirlineInfo("Ryanair", "FR"),
        "QFA" to AirlineInfo("Qantas", "QF"),
        "ACA" to AirlineInfo("Air Canada", "AC"),
        "ANZ" to AirlineInfo("Air New Zealand", "NZ"),
        "SIA" to AirlineInfo("Singapore Airlines", "SQ"),
        "CPA" to AirlineInfo("Cathay Pacific", "CX"),
        "ANA" to AirlineInfo("All Nippon Airways", "NH"),
        "JAL" to AirlineInfo("Japan Airlines", "JL"),
        "UAE" to AirlineInfo("Emirates", "EK"),
        "ETH" to AirlineInfo("Ethiopian Airlines", "ET"),
        "THY" to AirlineInfo("Turkish Airlines", "TK"),
        "CSN" to AirlineInfo("China Southern", "CZ"),
        "CCA" to AirlineInfo("Air China", "CA"),
        "CES" to AirlineInfo("China Eastern", "MU"),
        // India
        "AIC" to AirlineInfo("Air India", "AI"),
        "IGO" to AirlineInfo("IndiGo", "6E"),
        "SEJ" to AirlineInfo("SpiceJet", "SG"),
        "VTI" to AirlineInfo("Vistara", "UK"),
        "AXB" to AirlineInfo("Air India Express", "IX"),
        // Korea
        "KAL" to AirlineInfo("Korean Air", "KE"),
        "AAR" to AirlineInfo("Asiana Airlines", "OZ"),
        "JJA" to AirlineInfo("Jeju Air", "7C"),
        "JNA" to AirlineInfo("Jin Air", "LJ"),
        "TWB" to AirlineInfo("T'way Air", "TW"),
        // Latin America
        "LAN" to AirlineInfo("LATAM Airlines Chile", "LA"),
        "TAM" to AirlineInfo("LATAM Airlines Brasil", "JJ"),
        "GLO" to AirlineInfo("GOL Linhas Aereas", "G3"),
        "AVA" to AirlineInfo("Avianca", "AV"),
        "CMP" to AirlineInfo("Copa Airlines", "CM"),
        "AMX" to AirlineInfo("Aeromexico", "AM"),
        "ARG" to AirlineInfo("Aerolineas Argentinas", "AR"),
        "AZU" to AirlineInfo("Azul Brazilian Airlines", "AD"),
        "VOI" to AirlineInfo("Volaris", "Y4"),
        "VIV" to AirlineInfo("VivaAerobus", "VB"),
        // Middle East
        "QTR" to AirlineInfo("Qatar Airways", "QR"),
        "SVA" to AirlineInfo("Saudia", "SV"),
        "ETD" to AirlineInfo("Etihad Airways", "EY"),
        "OMA" to AirlineInfo("Oman Air", "WY"),
        "GFA" to AirlineInfo("Gulf Air", "GF"),
        "RJA" to AirlineInfo("Royal Jordanian", "RJ"),
        "MEA" to AirlineInfo("Middle East Airlines", "ME"),
        "ELY" to AirlineInfo("El Al", "LY"),
        "FDB" to AirlineInfo("flydubai", "FZ"),
        "ABY" to AirlineInfo("Air Arabia", "G9"),
        "KAC" to AirlineInfo("Kuwait Airways", "KU"),
        // Africa
        "SAA" to AirlineInfo("South African Airways", "SA"),
        "KQA" to AirlineInfo("Kenya Airways", "KQ"),
        "MSR" to AirlineInfo("EgyptAir", "MS"),
        "RAM" to AirlineInfo("Royal Air Maroc", "AT"),
        // Europe
        "SWR" to AirlineInfo("Swiss International Air Lines", "LX"),
        "IBE" to AirlineInfo("Iberia", "IB"),
        "IBS" to AirlineInfo("Iberia Express", "I2"),
        "TAP" to AirlineInfo("TAP Air Portugal", "TP"),
        "SAS" to AirlineInfo("Scandinavian Airlines", "SK"),
        "NAX" to AirlineInfo("Norwegian Air Shuttle", "DY"),
        "FIN" to AirlineInfo("Finnair", "AY"),
        "LOT" to AirlineInfo("LOT Polish Airlines", "LO"),
        "WZZ" to AirlineInfo("Wizz Air", "W6"),
        "AUA" to AirlineInfo("Austrian Airlines", "OS"),
        "BEL" to AirlineInfo("Brussels Airlines", "SN"),
        "EIN" to AirlineInfo("Aer Lingus", "EI"),
        "VLG" to AirlineInfo("Vueling", "VY"),
        "EXS" to AirlineInfo("Jet2.com", "LS"),
        "AEE" to AirlineInfo("Aegean Airlines", "A3"),
        "AEA" to AirlineInfo("Air Europa", "UX"),
        "PGT" to AirlineInfo("Pegasus Airlines", "PC"),
        "SXS" to AirlineInfo("SunExpress", "XQ"),
        "TOM" to AirlineInfo("TUI Airways", "BY"),
        "CFG" to AirlineInfo("Condor", "DE"),
        "AFL" to AirlineInfo("Aeroflot", "SU"),
        "SBI" to AirlineInfo("S7 Airlines", "S7"),
        "VOE" to AirlineInfo("Volotea", "V7"),
        "EJU" to AirlineInfo("easyJet Europe", "EC"),
        "TRA" to AirlineInfo("Transavia Airlines", "HV"),
        // Asia-Pacific
        "MAS" to AirlineInfo("Malaysia Airlines", "MH"),
        "GIA" to AirlineInfo("Garuda Indonesia", "GA"),
        "PAL" to AirlineInfo("Philippine Airlines", "PR"),
        "HVN" to AirlineInfo("Vietnam Airlines", "VN"),
        "VJC" to AirlineInfo("VietJet Air", "VJ"),
        "THA" to AirlineInfo("Thai Airways", "TG"),
        "CAL" to AirlineInfo("China Airlines", "CI"),
        "EVA" to AirlineInfo("EVA Air", "BR"),
        "AXM" to AirlineInfo("AirAsia", "AK"),
        "XAX" to AirlineInfo("AirAsia X", "D7"),
        "CEB" to AirlineInfo("Cebu Pacific", "5J"),
        "LNI" to AirlineInfo("Lion Air", "JT"),
        "HKE" to AirlineInfo("HK Express", "UO"),
        "APJ" to AirlineInfo("Peach Aviation", "MM"),
        "PIA" to AirlineInfo("Pakistan International Airlines", "PK"),
        "HDA" to AirlineInfo("Hainan Airlines", "HU"),
        "CSH" to AirlineInfo("Shanghai Airlines", "FM"),
        "CSZ" to AirlineInfo("Shenzhen Airlines", "ZH"),
        "CXA" to AirlineInfo("XiamenAir", "MF"),
        "CQH" to AirlineInfo("Spring Airlines", "9C"),
        "DKH" to AirlineInfo("Juneyao Air", "HO"),
        // Australia / New Zealand
        "JST" to AirlineInfo("Jetstar Airways", "JQ"),
        "VOZ" to AirlineInfo("Virgin Australia", "VA"),
        // North America regional/others
        "HAL" to AirlineInfo("Hawaiian Airlines", "HA"),
        "WJA" to AirlineInfo("WestJet", "WS"),
        "TSC" to AirlineInfo("Air Transat", "TS"),
        "ROU" to AirlineInfo("Air Canada Rouge", "RV"),
        "QXE" to AirlineInfo("Horizon Air", "QX"),
        "EDV" to AirlineInfo("Endeavor Air", "9E"),
        "ASH" to AirlineInfo("Mesa Airlines", "YV"),
        "PDT" to AirlineInfo("Piedmont Airlines", "PT"),
        "JIA" to AirlineInfo("PSA Airlines", "OH"),
        "SCX" to AirlineInfo("Sun Country Airlines", "SY"),
        "AAY" to AirlineInfo("Allegiant Air", "G4"),
        // Cargo
        "FDX" to AirlineInfo("FedEx Express", "FX"),
        "UPS" to AirlineInfo("UPS Airlines", "5X"),
        "CLX" to AirlineInfo("Cargolux Airlines", "CV"),
        "GTI" to AirlineInfo("Atlas Air", "5Y"),
        "CKS" to AirlineInfo("Kalitta Air", "K4"),
        "PAC" to AirlineInfo("Polar Air Cargo", "PO"),
        "NCA" to AirlineInfo("Nippon Cargo Airlines", "KZ"),
        "ABX" to AirlineInfo("ABX Air", "GB"),
        "CKK" to AirlineInfo("China Cargo Airlines", "CK"),
        "BOX" to AirlineInfo("AeroLogic", "3S"),
        "DHK" to AirlineInfo("DHL Air", "D0")
    )

    fun matchByCallsign(callsign: String): AirlineInfo? {
        if (callsign.length < 4) return null
        return PREFIXES[callsign.take(3).uppercase()]
    }
}
