#ifndef BACKEND_HARDWARE_PROFILE_H
#define BACKEND_HARDWARE_PROFILE_H

#include <stdint.h>

#if (defined(FOF_BACKEND_PROFILE_BADGE_LITE) + \
     defined(FOF_BACKEND_PROFILE_S3_FULLSIZE)) != 1
#error "select exactly one backend hardware profile"
#endif

#define FOF_BACKEND_FIRMWARE_LINE "backend"
#define FOF_BACKEND_SCANNER_UART_PORT 1
#define FOF_BACKEND_SCANNER_UART_BAUD 921600

#define FOF_BACKEND_STATUS_LED_TYPE_ACTIVE_LOW_GPIO 1
#define FOF_BACKEND_STATUS_LED_TYPE_WS2812 2

#if defined(FOF_BACKEND_PROFILE_BADGE_LITE)

#define FOF_BACKEND_PRODUCT_FAMILY "badge_lite"
#define FOF_BACKEND_HARDWARE "seeed_xiao_esp32s3"
#define FOF_BACKEND_UPLINK_TARGET "uplink-s3-backend"
#define FOF_BACKEND_UPLINK_PROJECT "fof_backend_uplink"
#define FOF_BACKEND_SCANNER_TARGET "scanner-s3-combo-backend"
#define FOF_BACKEND_SCANNER_PROJECT "fof_backend_scanner"
#define FOF_BACKEND_FLASH_SIZE_BYTES UINT32_C(0x800000)
#define FOF_BACKEND_UPLINK_APP_CAPACITY UINT32_C(0x200000)
#define FOF_BACKEND_SCANNER_OTA_CAPACITY UINT32_C(0x200000)
#define FOF_BACKEND_SCANNER_CACHE_CAPACITY UINT32_C(0x200000)
#define FOF_BACKEND_SCANNER_UART_TX_PIN 1
#define FOF_BACKEND_SCANNER_UART_RX_PIN 2
#define FOF_BACKEND_UPLINK_SLOT0_UART_RX_PIN 2
#define FOF_BACKEND_UPLINK_SLOT0_UART_TX_PIN 1
#define FOF_BACKEND_UPLINK_SLOT1_UART_RX_PIN 4
#define FOF_BACKEND_UPLINK_SLOT1_UART_TX_PIN 3
#define FOF_BACKEND_STATUS_LED_TYPE FOF_BACKEND_STATUS_LED_TYPE_ACTIVE_LOW_GPIO
#define FOF_BACKEND_STATUS_LED_GPIO 21

#else

#define FOF_BACKEND_PRODUCT_FAMILY "s3_fullsize"
#define FOF_BACKEND_HARDWARE "esp32s3_n16r8_fullsize"
#define FOF_BACKEND_UPLINK_TARGET "uplink-s3-fullsize-backend"
#define FOF_BACKEND_UPLINK_PROJECT "fof_backend_uplink_fullsize"
#define FOF_BACKEND_SCANNER_TARGET "scanner-s3-combo-fullsize-backend"
#define FOF_BACKEND_SCANNER_PROJECT "fof_backend_scanner_fullsize"
#define FOF_BACKEND_FLASH_SIZE_BYTES UINT32_C(0x1000000)
#define FOF_BACKEND_UPLINK_APP_CAPACITY UINT32_C(0x200000)
#define FOF_BACKEND_SCANNER_OTA_CAPACITY UINT32_C(0x300000)
#define FOF_BACKEND_SCANNER_CACHE_CAPACITY UINT32_C(0x300000)
#define FOF_BACKEND_SCANNER_UART_TX_PIN 17
#define FOF_BACKEND_SCANNER_UART_RX_PIN 18
#define FOF_BACKEND_UPLINK_SLOT0_UART_RX_PIN 18
#define FOF_BACKEND_UPLINK_SLOT0_UART_TX_PIN 17
#define FOF_BACKEND_UPLINK_SLOT1_UART_RX_PIN 16
#define FOF_BACKEND_UPLINK_SLOT1_UART_TX_PIN 15
#define FOF_BACKEND_STATUS_LED_TYPE FOF_BACKEND_STATUS_LED_TYPE_WS2812
#define FOF_BACKEND_STATUS_LED_GPIO 48

#endif

#endif
